spring.application.name=assessment4
spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment1
spring.datasource.username=postgres
spring.datasource.password=tithaye
server.port=8083
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false